
package aula12;

public class Aula12 {

     public static void main(String[] args) {
         Mamifero m = new Mamifero();
         Canguru c = new Canguru();
         Cachorro k = new Cachorro();
         Reptil r = new Reptil();
         Cobra co = new Cobra();
         Tartaruga t = new Tartaruga();
         Peixe p = new Peixe();
         Goldfish g = new Goldfish();
         Ave a = new Ave();
         Arara ar = new Arara();
         m.setPeso(85.3f);
         m.setIdade(2);
         m.setMembros(4);
         m.setCorPelo("preto");
         m.locomover();
         m.alimentar();
         m.emitirSom();
         System.out.println("---------------------");
         c.setPeso(55.3f);
         c.setIdade(3);
         c.setMembros(4);
         c.locomover();
         c.alimentar();
         c.emitirSom();
         c.usarBolsa();
         System.out.println("---------------------");
         k.setPeso(3.94f);
         k.setIdade(5);
         k.setMembros(4);
         k.locomover();
         k.alimentar();
         k.emitirSom();
         k.enterrarOsso();
         k.abanarRabo();
         System.out.println("---------------------");
         r.setPeso(0.0f);
         r.setIdade(0);
         r.setMembros(0);
         r.setCorEscama("Cinza");
         r.locomover();
         r.alimentar();
         r.emitirSom();
         System.out.println("---------------------");
         co.setPeso(0.0f);
         co.setIdade(0);
         co.setMembros(0);
         co.locomover();
         co.alimentar();
         co.emitirSom();
         System.out.println("---------------------");
         t.setPeso(0.0f);
         t.setIdade(0);
         t.setMembros(0);
         t.locomover();
         t.alimentar();
         t.emitirSom();
         System.out.println("---------------------");
         p.setPeso(0.35f);
         p.setIdade(1);
         p.setMembros(0);
         p.setCorEscama("Vermelho");
         p.locomover();
         p.alimentar();
         p.emitirSom();
         p.soltarBolha();
         System.out.println("---------------------");
         g.setPeso(0.0f);
         g.setIdade(0);
         g.setMembros(0);
         g.locomover();
         g.alimentar();
         g.emitirSom();
         g.soltarBolha();
         System.out.println("---------------------");
         a.setPeso(0.89f);
         a.setIdade(2);
         a.setMembros(2);
         a.setCorPena("Azul");
         a.locomover();
         a.alimentar();
         a.emitirSom();
         a.fazerNinho();
         System.out.println("---------------------");
         ar.setPeso(0.0f);
         ar.setIdade(0);
         ar.setMembros(0);
         ar.locomover();
         ar.alimentar();
         ar.emitirSom();
         ar.fazerNinho();
         System.out.println("---------------------");
    }
    
}
